-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customer
(
    id uuid NOT NULL DEFAULT gen_random_uuid (),
    code character varying(25) NOT NULL,
    name character varying(50) NOT NULL,
    family uuid,
    CONSTRAINT customer_id_pk PRIMARY KEY (id),
    CONSTRAINT customer_code_unique UNIQUE (code)
);

COMMENT ON TABLE public.customer
    IS 'Customer table';

CREATE TABLE IF NOT EXISTS public.customer_family
(
    id uuid NOT NULL DEFAULT gen_random_uuid (),
    code character varying(25) NOT NULL,
    description character varying(255),
    CONSTRAINT customer_id_pk PRIMARY KEY (id),
    CONSTRAINT customer_family_code_unique UNIQUE (code)
);

COMMENT ON TABLE public.customer_family
    IS 'Customers families';

CREATE TABLE IF NOT EXISTS public."order"
(
    id uuid NOT NULL DEFAULT gen_random_uuid (),
    customer uuid NOT NULL,
    product uuid NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT order_id_pk PRIMARY KEY (id)
);

COMMENT ON TABLE public."order"
    IS 'Order table';

CREATE TABLE IF NOT EXISTS public.product
(
    id uuid NOT NULL DEFAULT gen_random_uuid (),
    code character varying(25) NOT NULL,
    name character varying(50) NOT NULL,
    CONSTRAINT product_id_pk PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.customer
    ADD CONSTRAINT customer_family_fk FOREIGN KEY (family)
    REFERENCES public.customer_family (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_customer FOREIGN KEY (customer)
    REFERENCES public.customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_product FOREIGN KEY (product)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;